### ISSUE TITLE
[BUG] If the description field for a Tool is too long, it breaks

### ISSUE THREAD

**Issue by ion-storm** [logspace-ai/langflow#132] opened 2023-04-07 20:42 UTC
I receive this error when putting in a long descriptive description in the new tool widget:
There was an error loading the langchain_object. Please, check all the nodes and try again.

**Comment by anovazzi1** [comment] 2023-04-09 12:21
i will check this, but I think its's caused by other thing than the long description

**Comment by hunter-meloche** [comment] 2023-04-13 02:49
I'm noticing this even when I simply try to add a memory buffer, as well as whenever I try to use Python functions.

**Comment by qixiaobo** [comment] 2023-04-13 04:22
Same problem
![image](https://user-images.githubusercontent.com/2881751/231652324-b93f032d-d716-4101-be8f-2cd4ed4949bb.png)

**Comment by ibiscp** [comment] 2023-04-14 14:08
Could you please test again in the last version [v0.0.56](https://github.com/logspace-ai/langflow/releases/tag/v0.0.56), and let us know if you still find this error? If yes, please post an image of the flow or JSON here.

I will close it for now because there was a bug with the tools in one of the versions, please reopen it if the error persists.

**Closed by ibiscp** 2023-04-14 14:08 UTC
