### ISSUE TITLE
Conflict dependencies

### ISSUE THREAD

**Issue by BrandenAdems** [logspace-ai/langflow#866] opened 2023-09-05 05:00 UTC
**Describe the bug**

**Browser and Version**
 - Browser [opera GX]
 - Version [101.0.4843.81]

**To Reproduce**
1. Go to 'Anaconda prompt, create a new environment with python=3.9.'
2. Activate Environment
3. "pip install langflow" following the instructions

![image](https://github.com/logspace-ai/langflow/assets/88533031/c4098dcb-602a-4333-988a-800624c6b00e)

I tried to install the packages manually but it will overwrite the previous version that was installed.

**Comment by songw** [comment] 2023-09-05 05:58
I have the same error.

**Comment by dustyatx** [comment] 2023-09-05 19:04
Same.. I'm also wondering about what telemetry is being shared.

**Comment by ojaragodwin** [comment] 2023-09-05 20:54
Same error as well

**Comment by niklaspm** [comment] 2023-09-06 00:23
duplicate of #864

> The issue is caused by the Jina package. The fix (https://github.com/jina-ai/jina/pull/6037) has already been merged into Jina's master branch, but until they've released the changes to the package, the easiest way to install LangFlow is to clone the repo and add `opentelemetry-sdk = ">=1.14.0,<1.20.0"` to the dependencies listed in `pyproject.toml`  and then install the package using `pip install .` from within the cloned repo's base directory.

**Comment by dustyatx** [comment] 2023-09-06 03:52
I've been trying to get the workaround working but add the opentelemetry to the toml file just brought me the next errors. 

The current one is the webserver starts but a blank page loads, the I get a error saying javascript isn't enabled (it is) in the browser console. Not sure what the issue, in the terminal I see that it says failed to load this module.  I have it installed.. 
Failed to load module "canberra-gtk-module"

Not sure if something to do with running PopOS or if this is related to the decencies issues. I'm a bit bandwidth constrained so I can't go deep troubleshooting. would really appreciate if someone who knows this project can do a fresh install and see if the workaround gets them running properly or if they have similar issues I'm having.

**Comment by estkae** [comment] 2023-09-06 06:21
I installed Langflow after the initial installation on POPOS and it worked. I suspect that conda was still on 2.7. Python 3.10 installed. After that I have on conda 23.x and Paython 3.10 since then it no longer works. Now i use Docker.

**Comment by rodgermoore** [comment] 2023-09-06 20:00
This worked for me using Docker build:

https://github.com/logspace-ai/langflow/issues/864#issuecomment-1707883060

**Comment by KewkLW** [comment] 2023-09-06 23:45
The fix is live in the jina repo. https://github.com/jina-ai/jina/pull/6037 

Clone their repo 

https://github.com/jina-ai/jina.git

Create a venv

Activate it 

cd to the jina dir 

pip install . 

Then pip install langflow

**Comment by BrandenAdems** [comment] 2023-09-07 02:00
Thank you @KewkLW ! It work like a charm.

**Closed** 2023-09-07 02:00 UTC

**Comment by estkae** [comment] 2023-09-07 05:10
This work also in popos:
pip3 install "opentelemetry-sdk >=1.14.0,<1.20.0" langflow
Thanks a lot.
