### ISSUE TITLE
UI Does not load. 

### ISSUE THREAD

**Issue by Acidbuk** [logspace-ai/langflow#345] opened 2023-05-25 03:48 UTC
**Describe the bug**
I activate the server I get this: 
[03:57:35] INFO     [03:57:35] - INFO - Logger set up with log level: 20(info)                             logger.py:28
           INFO     [03:57:35] - INFO - Log file: logs\langflow.log                                        logger.py:30
←[32mINFO←[0m:     Started server process [←[36m34988←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:7860←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     127.0.0.1:57223 - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:57223 - "←[1mGET /assets/index-e39661aa.js HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:57224 - "←[1mGET /assets/index-d5403acc.css HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:57224 - "←[1mGET /favicon.ico HTTP/1.1←[0m" ←[32m200 OK←[0m

When I load the localhost URL (127.0.0.1:7860) into my browser I get a blank screen. I am. fairly certain it is not supposed to be putting "1m" in front of everything?. I am running in a miniconda Virtual Environment

**Browser and Version**
 - Browser : Firefox 113.0.0 64Bit, also testing with Edge 113.0.1774.50 (Official build) (64-bit)

**To Reproduce**
Steps to reproduce the behaviour:
1 conda create langflow
2 conda activate langflow
3 pip install langflow
4 python -m langflow
4 Type http://127.0.0.1:7860 to URL bar
See error (Blank Screen)

**Comment by caudurodev** [comment] 2023-05-25 07:04
I had the same issue and to get the interface working I created a new named tab - possibly related to the root cause.

**Comment by Acidbuk** [comment] 2023-05-25 07:29
Could you walk me through how to do that please?

**Comment by gogi2811** [comment] 2023-06-03 15:09
Facing the same issue , any resolutions?

**Comment by ogabrielluiz** [comment] 2023-06-04 21:06
This issue is a duplicate. I'm closing this one in favor of #353. Please try deleting cookies and cache and reporting in that issue.

**Closed by ogabrielluiz** 2023-06-04 21:06 UTC
