### ISSUE TITLE
how to find  the username and password of superuser

### ISSUE THREAD

**Issue by yuec** [logspace-ai/langflow#875] opened 2023-09-05 16:11 UTC
**Describe the bug**

**Browser and Version**

**To Reproduce**
1. Open the app for the first time
2. Login as the superuser

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/4444125/0b69614a-7f3f-404e-83fe-cadfab83ecb6)

I dont know how to find  the username and password of superuser. 
i try langflow langflow,but it is not success

**Comment by niklaspm** [comment] 2023-09-05 21:34
duplicate of #854. Use `langflow superuser` to create a new user having superpowers.

**Comment by yuec** [comment] 2023-09-06 00:08
> duplicate of #854. Use `langflow superuser` to create a new user having superpowers.

Thank you, problem solved.

use `docker exec -it {langflow_backend container id} langflow superuser` to create admin username and password

**Closed** 2023-09-06 00:09 UTC
