### ISSUE TITLE
LANGFLOW_LANGFUSE_HOST is not available

### ISSUE THREAD

**Issue by 447264188** [logspace-ai/langflow#947] opened 2023-09-21 09:25 UTC
**Describe the bug**
If i am self-hosting Langfuse, i set the environment variable `LANGFLOW_LANGFUSE_HOST` to point to my Langfuse instance. 
but it is not available. it is still point to default Langfuse instance  at `https://cloud.langfuse.com`.

**Version**
langflow == 0.4.20

**Solution**
Add a line of code in langflow/services/plugins/langfuse.py
![20230921-171909](https://github.com/logspace-ai/langflow/assets/47591121/a790a83c-380a-43f7-b2a8-642f59e2c9f0)

**Comment by yassineselmi** [comment] 2023-09-21 15:26
Duplicate of #942

**Closed** 2023-09-22 15:44 UTC
